---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: blms-deployment
  labels:
    app: blms-deployment
  namespace: tech-coe-dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: blms
  template:
    metadata:
      labels:
        app: blms
    spec:
      containers:
      - name: blms
        image: uemdevopsid/blms:<IMAGE_VERSION>
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: regcred

---
apiVersion: v1
kind: Service
metadata:
  name: blms-service
  namespace: tech-coe-dev
spec:
  selector:
    app: blms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: blms-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /
  namespace: tech-coe-dev
spec:
  rules:
  - host: "blms.uemedgenta-dev.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: blms-service
            port:
              number: 80
