name: blmsv1-release-branch-pipeline
on:
  push:
    branches:
      - 'releases/**'
jobs:
  build-and-test:

    runs-on: [self-hosted, azure]

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core SDK 
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --no-restore --verbosity normal

  docker-build-and-push:
    name: Docker Build And Push
    runs-on: [self-hosted, azure]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/releases/})"
        id: extract_branch
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/blms:${{ steps.extract_branch.outputs.branch }}

  deploy-app-prod:
    name: Deploy App to Prod Azure AKS Cluster
    runs-on: [self-hosted, azure]
    needs: [docker-build-and-push, build-and-test]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.2.0
      - name: Decrypt kube_config file
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase=${{ secrets.GPG_PASSPHRASE }} --output ./kube_config/aks-its-app-github-action-sa.yml ./kube_config/aks-its-app-github-action-sa.yml.gpg
          ls ./kube_config
      - name: Create Database Connection String Secret
        run: |
          export KUBECONFIG=./kube_config/aks-its-app-github-action-sa.yml
          kubectl create secret generic blms-db-connstr -n tech-coe-prod --from-literal=SQLCONNSTR_DBConnection=${{ secrets.PROD_DBCONNECTION }} --dry-run=client -o=yaml | kubectl apply -f -
      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/releases/})"
        id: extract_branch
      - name: Deploy application to Prod kubernetes cluster
        run: |
          export KUBECONFIG=./kube_config/aks-its-app-github-action-sa.yml
          sed -i "s/<IMAGE_VERSION>/${{ steps.extract_branch.outputs.branch }}/g" blms-deployment-prod.yml
          kubectl -n tech-coe-prod apply -f blms-deployment-prod.yml