#main-pipeline
name: blmsv1-main-branch-pipeline
on:
 push:
  branches:
   - 'main'
jobs:
 sonerqube-scan:
  name: SonarQube Scan
  runs-on: [self-hosted, onprem]
  needs: [docker-build-and-push]

  steps:
   - run: echo "Run SonerQube scan"
   
 docker-build-and-push:
  name: Docker Build And Push
  runs-on: [self-hosted, onprem]

  steps:
   - run: echo "docker-build-and-push"

 deploy-app-dev:
  name: Deploy App to Dev Rancher Cluster
  runs-on: [self-hosted, onprem]
  needs: [docker-build-and-push]

  steps:
   - run: echo "Deploy to dev"



